### ISSUE TITLE
 Unable to locate package libsqlite3-mod-spatialite

### ISSUE THREAD

**Issue by arvindshmicrosoft** [jlmcgraw/processFaaData#1]
hi Jim,
Am getting an error when trying to setup on Ubuntu 14.04, setup.sh fails:

 Unable to locate package libsqlite3-mod-spatialite

Any suggestions?

**Comment by jlmcgraw** [comment]
I don't know the details as to why but something changed with how spatialite extension is loaded into sqlite in more recent versions

A couple of options:

```
a) You can try with a more recent version of Ubuntu (which includes newer sqlite)

b) Try installing "libspatialite3" instead of "libsqlite3-mod-spatialite" in setup.sh, and adjust sqliteToSpatialite.sql as follows:
```

-- The old way of loading spatialite
 SELECT load_extension('libspatialite.so');
-- The new way
-- See https://www.gaia-gis.it/fossil/libspatialite/wiki?name=mod_spatialite
-- SELECT load_extension('mod_spatialite');

**Comment by arvindsh** [comment]
Thanks Jesse. I downloaded the DEB file for libspatialite3 and then used dpkg to install it. That seems to have fixed this.

**Comment by jlmcgraw** [comment]
I don't know the details as to why but something changed with how 
spatialite extension is loaded into sqlite in more recent versions

A couple of options:

```
 a) You can try with a more recent version of Ubuntu

 b) Try installing "libspatialite3" instead, and adjust 
```

sqliteToSpatialite.sql as follows:

-- The old way of loading spatialite
  SELECT load_extension('libspatialite.so');
-- The new way
-- See https://www.gaia-gis.it/fossil/libspatialite/wiki?name=mod_spatialite
-- SELECT load_extension('mod_spatialite');

Let me know how it goes

-Jesse
