### ISSUE TITLE
Lack of LICENSE file or terms of use

### ISSUE THREAD

**Issue by aweinert-MIT** [jlmcgraw/processFaaData#10]
I am potentially interested in using this repository but there is no formal LICENSE or terms of use. I can't and won't use the repository without a license.

To resolve this issue, I recommend adding a LICENSE file and assigning a permissive open source license, such as BSD-2 or MIT.

This is a good resource in helping to select a license: https://choosealicense.com/

**Comment by jlmcgraw** [comment]
Added GPLv3 license
