### ISSUE TITLE
Updated parser for NASR files March 2022

### ISSUE THREAD

**Issue by sentrid** [jlmcgraw/processFaaData#13]
I've attached the updated parser file to process the NASR data files as of March 2022. Hope it helps someone.

[hash_of_parsers.pl.zip](https://github.com/jlmcgraw/processFaaData/files/8188398/hash_of_parsers.pl.zip)

**Comment by jlmcgraw** [comment]
This file is identical to the current one.  If you want to submit a pull request I'd be happy to incorporate the changes

**Comment by jlmcgraw** [comment]
Merged PR addresses data layout updates effective 2022-03-24
