### ISSUE TITLE
Line # 1 - Bad parse for OBSTACLE: Expected 122 characters but read 128

### ISSUE THREAD

**Issue by geospatialmapmashup** [jlmcgraw/processFaaData#3]
was trying to process 28DaySubscription_Effective_2017-12-07.zip
and I got the following error:
Loading NAV: 9000...

Line # 1 - Bad parse for OBSTACLE: Expected 122 characters but read 128

**Comment by jlmcgraw** [comment]
The FAA updated the obstacle data format (see https://www.faa.gov/air_traffic/flight_info/aeronav/obst_data/)

I updated code to handle this back in [June](https://github.com/jlmcgraw/processFaaData/commit/539c8326261759000acac518e37f39437094bd7a#diff-90167ec676f542570f9d7af94b3510be), are you using a recent version?
