### ISSUE TITLE
error command not found

### ISSUE THREAD

**Issue by geospatialmapmashup** [jlmcgraw/processFaaData#4]
geodata@GEO02:/mnt/l/process_faa_nasr_data$ ./create_databases.sh 28DaySubscription_Effective_2017-12-07.zip
./create_databases.sh: line 4: $'\r': command not found

I did a git pull to grab the latest and now I am getting this weird issue.
I opened create_databases.sh and I don't see that line or 'r'
I am running Bash for Windows Ubuntu on Windows 10 Pro.
I've tried running from Bash shell or command prompt
bash -c "cd /mnt/l/process_faa_nasr_data && ./create_databases.sh 28DaySubscription_Effective_2017-12-07.zip"
./create_databases.sh: line 4: $'\r': command not found

**Comment by jlmcgraw** [comment]
Perhaps it’s a Windows vs. Linux line-ending issue.    Can your editor
change between those two?  If so, try editing the script and saving it with
Windows line endings.

I haven’t tested this under anything but various Linux VMs so I don’t know
how it’ll work with Windows

**Comment by geospatialmapmashup** [comment]
I did a websearch and looks like a common problem with WSL -Windows Subsystem for Linux (Bash for Windows).   I run many tools as part of Bash for windows and never experienced a problem.  I guess it's time to fire up my Hyper-V Ubuntu VM to resolve this. I see that ATOM text editor has a Line Ending Selector Package.
