### ISSUE TITLE
Parse error loading ARB records

### ISSUE THREAD

**Issue by ssokol** [jlmcgraw/processFaaData#5]
Running into a parse error with the latest (28DaySubscription_Effective_2018-09-13.zip) file. I'm using the latest version of the tool.

```
Loading ARB: 2000...

Line # 1 - ATS1ATA300             1009/13/2018                   000.00000.00                  06000              BND                       BND         BND         ZSURAYAS*OA                                ATA300        *RAYAS*OA                                              BND                                                                           0000001 -
 Bad parse for ATS1: Expected 327 characters but read 350
```

Any suggestions?

**Comment by ssokol** [comment]
Correction, looks like the error is actually in the ATS file.

**Comment by jlmcgraw** [comment]
Several record types were modified by FAA recently.  I’ve updated the
parsers this morning so try the most recent code and let me know how it
works
