### ISSUE TITLE
Dropbox link in the README is 404

### ISSUE THREAD

**Issue by justinclift** [jlmcgraw/processFaaData#7]
Stumbled over this again, and decided to grab the data to take a look at again, as it was useful back in the day. :smile:

The Dropbox link in the README is 404 though:

&nbsp; &nbsp; https://www.dropbox.com/s/j018ph69x9nduv4/data.tar.xz

**Comment by jlmcgraw** [comment]
I can recreate it, if it’s helpful

**Comment by justinclift** [comment]
Thanks, that would be useful. :smile:

**Comment by jlmcgraw** [comment]
Updated the link, try it now

https://www.dropbox.com/s/ichzdozjoco4jzj/2019-09-12-nasr_databases.zip?dl=0

**Comment by justinclift** [comment]
Thanks @jlmcgraw, link works again now. :smile:
